CREATE TABLE CONCORRENTE
(
    ID_COMPRA INT NOT NULL,
    ID_ESTADO_CIVIL INT NOT NULL,
    ID_LOCAL INT NOT NULL,
    ID_DATA INT NOT NULL,
    ID_APARELHO INT NOT NULL,
    VALOR FLOAT NOT NULL,
    QUANTIDADE  INT NOT NULL
);