CREATE TABLE TB_OLAP_FAT_COMPRA
(
    ID_COMPRA INT NOT NULL,
    ID_ESTADO_CIVIL INT NOT NULL,
    ID_LOCAL INT NOT NULL,
    ID_DATA INT NOT NULL,
    ID_APARELHO INT NOT NULL,
    VALOR FLOAT NOT NULL,
    QUANTIDADE  INT NOT NULL
);

ALTER TABLE TB_OLAP_FAT_COMPRA ADD CONSTRAINT PK_OLAP_FAT_COMPRA PRIMARY KEY (ID_COMPRA);


CREATE TABLE TB_OLAP_DIM_LOCAL
(
    ID_LOCAL  INT NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL
);

ALTER TABLE TB_OLAP_DIM_LOCAL ADD CONSTRAINT PK_OLAP_DIM_LOCAL PRIMARY KEY (ID_LOCAL);
CREATE SEQUENCE SQ_OLAP_LOCAL;

CREATE TABLE TB_OLAP_DIM_DATA
(
    ID_DATA INT NOT NULL,
    QUADRIMESTRE INT NOT NULL,
    ANO INT NOT NULL
);

ALTER TABLE TB_OLAP_DIM_DATA ADD CONSTRAINT PK_OLAP_DIM_DATA PRIMARY KEY (ID_DATA);
CREATE SEQUENCE SQ_OLAP_DATA;

CREATE TABLE TB_OLAP_DIM_ESTADO_CIVIL
(
    ID_ESTADO_CIVIL INT NOT NULL,
    ESTADO_CIVIL INT NOT NULL -- 0: SOLTEIRO | 1: CASADO | 2: VIUVO | 3: UNIAO ESTAVEL
);

ALTER TABLE TB_OLAP_DIM_ESTADO_CIVIL ADD CONSTRAINT PK_OLAP_DIM_CLIENTE PRIMARY KEY (ID_ESTADO_CIVIL);
CREATE SEQUENCE SQ_OLAP_CLIENTE;

CREATE TABLE TB_OLAP_DIM_APARELHO
(
    ID_APARELHO INT NOT NULL,
    MODELO VARCHAR(15) NOT NULL,
    MARCA VARCHAR(15) NOT NULL
);

ALTER TABLE TB_OLAP_DIM_APARELHO ADD CONSTRAINT PK_OLAP_DIM_APARELHO PRIMARY KEY (ID_APARELHO);
CREATE SEQUENCE SQ_OLAP_APARELHO;

ALTER TABLE TB_OLAP_FAT_COMPRA ADD CONSTRAINT FK_OLAP_COMPRA_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES TB_OLAP_DIM_LOCAL(ID_LOCAL);
ALTER TABLE TB_OLAP_FAT_COMPRA ADD CONSTRAINT FK_OLAP_COMPRA_DATA FOREIGN KEY (ID_DATA) REFERENCES TB_OLAP_DIM_DATA(ID_DATA);
ALTER TABLE TB_OLAP_FAT_COMPRA ADD CONSTRAINT FK_OLAP_COMPRA_CLIENTE FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES TB_OLAP_DIM_ESTADO_CIVIL(ID_ESTADO_CIVIL);
ALTER TABLE TB_OLAP_FAT_COMPRA ADD CONSTRAINT FK_OLAP_COMPRA_APARELHO FOREIGN KEY (ID_APARELHO) REFERENCES TB_OLAP_DIM_APARELHO(ID_APARELHO);
CREATE SEQUENCE SQ_OLAP_COMPRA;

-- CORREÇÕES OLTP
UPDATE CLIENTE SET ID_CIDADE = 5 WHERE ID_CIDADE = 30;
UPDATE CLIENTE SET ID_CIDADE = 19 WHERE ID_CIDADE = 37;
UPDATE CLIENTE SET ID_CIDADE = 25 WHERE ID_CIDADE = 35;