-- COMO EXTRAIR DADOS DE JSON NO LIVESQL?
-- COMO POSSO INSERIR OS LOCAIS E DATAS NO OLAP? IRIA FAZER COMPARAÇÃO DE UM EM UM NAS TABELAS OLTP E INSERINDO NO ID REFERENTE?
-- COMO TRANSFERIR A DATA SE ELA NÃO PRESERVA OS ATRIBUTOS?

-- TRANSFERINDO LOCAIS
CREATE OR REPLACE PROCEDURE TRANSFERIR_LOCAIS AS
BEGIN
    INSERT INTO TB_OLAP_DIM_LOCAL (ID_LOCAL, CIDADE, ESTADO)
    SELECT SQ_OLAP_LOCAL.NEXTVAL, C.DESCRICAO, E.SIGLA  
    FROM CIDADE C 
    JOIN ESTADO E USING (ID_ESTADO) 
    WHERE C.DESCRICAO <> 'SSA' AND C.DESCRICAO <> 'SP';

    COMMIT;
END;
EXEC TRANSFERIR_LOCAIS;

-- TRANSFERINDO APARELHOS
CREATE OR REPLACE PROCEDURE TRANSFERIR_APARELHOS AS
BEGIN
    INSERT INTO TB_OLAP_DIM_APARELHO (ID_APARELHO, MODELO, MARCA)
    SELECT SQ_OLAP_APARELHO.NEXTVAL, MO.DESCRICAO, MA.DESCRICAO FROM APARELHO A JOIN MODELO MO USING (ID_MODELO) JOIN MARCA MA  USING (ID_MARCA);

    COMMIT;
END;
EXEC TRANSFERIR_APARELHOS;

-- TRANSFERINDO DATAS
DECLARE
    CURSOR C1 IS SELECT DATA FROM C##OLTP.COMPRA;
BEGIN
    FOR TUPLA IN C1 LOOP
        IF (EXTRACT(MONTH FROM C1.DATA)) <= 4
            INSERT INTO TB_OLAP_DIM_DATA (ID_DATA, QUADRIMESTRE, ANO) VALUES SQ_OLAP_DATA.NEXTVAL, 1, EXTRACT(YEAR FROM C1.DATA);
        ENDIF;
        IF (EXTRACT(MONTH FROM C1.DATA)) > 4 AND EXTRACT(MONTH FROM C1.DATA) <= 8
            INSERT INTO TB_OLAP_DIM_DATA (ID_DATA, QUADRIMESTRE, ANO) VALUES SQ_OLAP_DATA.NEXTVAL, 2, EXTRACT(YEAR FROM C1.DATA);
        ENDIF;
        IF (EXTRACT(MONTH FROM C1.DATA)) >= 8
            INSERT INTO TB_OLAP_DIM_DATA (ID_DATA, QUADRIMESTRE, ANO) VALUES SQ_OLAP_DATA.NEXTVAL, 3, EXTRACT(YEAR FROM C1.DATA);
        ENDIF;
    ENDLOOP;
END;

BEGIN
-- PEGAR TODOS OS ATRIBUTOS DA TABELA FATO OLAP NUM SELECT NA OLTP E ENTAO AGREGAR TUDO PELOS ATRIBUTOS
SELECT NOME, DATA, CIDADE.DESCRICAO, MODELO.DESCRICAO FROM CARRINHO JOIN COMPRA USING (ID_COMPRA) JOIN APARELHO USING (ID_APARELHO) JOIN CLIENTE USING (ID_CLIENTE) JOIN MODELO USING (ID_MODELO) JOIN MARCA USING (ID_MARCA) JOIN CIDADE USING (ID_CIDADE) JOIN ESTADO USING (ID_ESTADO)