-- COMO EXTRAIR DADOS DE JSON NO LIVESQL?
-- COMO POSSO INSERIR OS LOCAIS E DATAS NO OLAP? IRIA FAZER COMPARAÇÃO DE UM EM UM NAS TABELAS OLTP E INSERINDO NO ID REFERENTE?
-- COMO TRANSFERIR A DATA SE ELA NÃO PRESERVA OS ATRIBUTOS?

-- TRANSFERINDO LOCAIS
BEGIN
    INSERT INTO TB_OLAP_DIM_LOCAL (ID_LOCAL, CIDADE, ESTADO)
    SELECT SQ_OLAP_LOCAL.NEXTVAL, C.DESCRICAO, E.SIGLA  
    FROM CIDADE C 
    JOIN ESTADO E USING (ID_ESTADO) 
    WHERE C.DESCRICAO <> 'SSA' AND C.DESCRICAO <> 'SP';

    COMMIT;
END;


-- TRANSFERINDO APARELHOS
BEGIN
    INSERT INTO TB_OLAP_DIM_APARELHO (ID_APARELHO, MODELO, MARCA)
    SELECT 
        SQ_OLAP_APARELHO.NEXTVAL, 
        MO.DESCRICAO, 
        MA.DESCRICAO
    FROM APARELHO A 
    JOIN MODELO MO USING (ID_MODELO) 
    JOIN MARCA MA USING (ID_MARCA)
    WHERE NOT EXISTS (
        SELECT 1 FROM TB_OLAP_DIM_APARELHO T
        WHERE T.MODELO = MO.DESCRICAO AND T.MARCA = MA.DESCRICAO
    );

    COMMIT;
END;

-- TRANSFERINDO DATAS
INSERT INTO TB_OLAP_DIM_DATA (ID_DATA, ANO, QUADRIMESTRE)
SELECT 
    SQ_OLAP_DATA.NEXTVAL,
    ANO,
    QUADRIMESTRE
FROM (
    SELECT DISTINCT
        EXTRACT(YEAR FROM DATA) AS ANO,
        CASE 
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
        END AS QUADRIMESTRE
    FROM COMPRA
) SUB;

-- TRANSFERINDO ESTADO CIVIL
INSERT INTO TB_OLAP_DIM_ESTADO_CIVIL (ID_ESTADO_CIVIL, ESTADO_CIVIL)
SELECT SQ_OLAP_ESTADO_CIVIL.NEXTVAL, ESTADO_CIVIL
FROM (
    SELECT DISTINCT ESTADO_CIVIL FROM CLIENTE
) C
WHERE NOT EXISTS (
    SELECT 1 FROM TB_OLAP_DIM_ESTADO_CIVIL T
    WHERE T.ESTADO_CIVIL = C.ESTADO_CIVIL
);

SELECT * FROM COMPRA JOIN CARRINHO USING (ID_COMPRA) JOIN CLIENTE USING (ID_CLIENTE) JOIN APARELHO USING (ID_APARELHO) JOIN CIDADE USING (ID_CIDADE) JOIN MODELO MO USING (ID_MODELO);

SELECT 
    ESTADO_CIVIL,
    MO.DESCRICAO AS MODELO,
    CIDADE.DESCRICAO AS CIDADE,
    ESTADO.SIGLA AS ESTADO,
    EXTRACT(YEAR FROM DATA) AS ANO,
    CASE 
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
    END AS quadrimestre,
    COUNT(*) AS QUANTIDADE,
    SUM(valor) AS VALOR
FROM COMPRA 
    JOIN CARRINHO USING (ID_COMPRA) 
    JOIN CLIENTE USING (ID_CLIENTE) 
    JOIN APARELHO USING (ID_APARELHO) 
    JOIN CIDADE USING (ID_CIDADE) 
    JOIN MODELO MO USING (ID_MODELO) 
    JOIN ESTADO USING (ID_ESTADO)
GROUP BY
    ESTADO_CIVIL,
    MO.DESCRICAO,
    CIDADE.DESCRICAO,
    ESTADO.SIGLA,
    EXTRACT(YEAR FROM DATA),
    CASE 
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
    END
ORDER BY 
    ANO,
    quadrimestre;


