-- COMO EXTRAIR DADOS DE JSON NO LIVESQL?
-- COMO POSSO INSERIR OS LOCAIS E DATAS NO OLAP? IRIA FAZER COMPARAÇÃO DE UM EM UM NAS TABELAS OLTP E INSERINDO NO ID REFERENTE?
-- COMO TRANSFERIR A DATA SE ELA NÃO PRESERVA OS ATRIBUTOS?

-- TRANSFERINDO LOCAIS
BEGIN
    INSERT INTO TB_OLAP_DIM_LOCAL (ID_LOCAL, CIDADE, ESTADO)
    SELECT SQ_OLAP_LOCAL.NEXTVAL, C.DESCRICAO, E.SIGLA  
    FROM CIDADE C 
    JOIN ESTADO E USING (ID_ESTADO) 
    WHERE C.DESCRICAO <> 'SSA' AND C.DESCRICAO <> 'SP';

    COMMIT;
END;


-- TRANSFERINDO APARELHOS

INSERT INTO TB_OLAP_DIM_APARELHO (ID_APARELHO, MODELO, MARCA) 
    SELECT 
        SQ_OLAP_APARELHO.NEXTVAL, 
        DESC_MODELO, 
        DESC_MARCA
    FROM (SELECT DISTINCT MODELO.DESCRICAO AS DESC_MODELO, MARCA.DESCRICAO AS DESC_MARCA FROM APARELHO JOIN MODELO USING (ID_MODELO) JOIN MARCA USING (ID_MARCA));

-- TRANSFERINDO DATAS
INSERT INTO TB_OLAP_DIM_DATA (ID_DATA, ANO, QUADRIMESTRE)
SELECT 
    SQ_OLAP_DATA.NEXTVAL,
    ANO,
    QUADRIMESTRE
FROM (
    SELECT DISTINCT
        EXTRACT(YEAR FROM DATA) AS ANO,
        CASE 
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
        END AS QUADRIMESTRE
    FROM COMPRA
) SUB;

-- TRANSFERINDO ESTADO CIVIL
INSERT INTO TB_OLAP_DIM_ESTADO_CIVIL (ID_ESTADO_CIVIL, ESTADO_CIVIL)
SELECT SQ_OLAP_ESTADO_CIVIL.NEXTVAL, ESTADO_CIVIL
FROM (
    SELECT DISTINCT ESTADO_CIVIL FROM CLIENTE
) C
WHERE NOT EXISTS (
    SELECT 1 FROM TB_OLAP_DIM_ESTADO_CIVIL T
    WHERE T.ESTADO_CIVIL = C.ESTADO_CIVIL
);

-- CRIANDO TABELA FATO
CREATE OR REPLACE PROCEDURE prc_popula_fat_compra AS
  v_id_estado_civil       TB_OLAP_DIM_ESTADO_CIVIL.ID_ESTADO_CIVIL%TYPE;
  v_id_local              TB_OLAP_DIM_LOCAL.ID_LOCAL%TYPE;
  v_id_data               TB_OLAP_DIM_DATA.ID_DATA%TYPE;
  v_id_aparelho           TB_OLAP_DIM_APARELHO.ID_APARELHO%TYPE;  
  CURSOR cur_agregados IS
    SELECT 
        ESTADO_CIVIL,
        MO.DESCRICAO AS MODELO,
        CIDADE.DESCRICAO AS CIDADE,
        ESTADO.SIGLA AS ESTADO,
        EXTRACT(YEAR FROM DATA) AS ANO,
        CASE 
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
        END AS quadrimestre,
        COUNT(*) AS QUANTIDADE,
        SUM(VALOR) AS VALOR
    FROM COMPRA 
         JOIN CARRINHO USING (ID_COMPRA) 
         JOIN CLIENTE USING (ID_CLIENTE) 
         JOIN APARELHO USING (ID_APARELHO) 
         JOIN CIDADE USING (ID_CIDADE) 
         JOIN MODELO MO USING (ID_MODELO) 
         JOIN ESTADO USING (ID_ESTADO)
    GROUP BY
        ESTADO_CIVIL,
        MO.DESCRICAO,
        CIDADE.DESCRICAO,
        ESTADO.SIGLA,
        EXTRACT(YEAR FROM DATA),
        CASE 
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
            WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
        END
    ORDER BY 
        ANO,
        quadrimestre;
        
BEGIN
  FOR rec IN cur_agregados LOOP

    SELECT ID_ESTADO_CIVIL 
      INTO v_id_estado_civil 
      FROM TB_OLAP_DIM_ESTADO_CIVIL
     WHERE ESTADO_CIVIL = rec.ESTADO_CIVIL
     AND ROWNUM = 1;

    SELECT ID_LOCAL 
      INTO v_id_local
      FROM TB_OLAP_DIM_LOCAL
     WHERE CIDADE = rec.CIDADE
       AND ESTADO  = rec.ESTADO
       AND ROWNUM = 1;
       
    SELECT ID_DATA 
      INTO v_id_data
      FROM TB_OLAP_DIM_DATA
     WHERE ANO = rec.ANO
       AND QUADRIMESTRE = rec.quadrimestre
       AND ROWNUM = 1;

    SELECT ID_APARELHO 
      INTO v_id_aparelho
      FROM TB_OLAP_DIM_APARELHO
     WHERE MODELO = rec.MODELO
     AND ROWNUM = 1; 
    INSERT INTO TB_OLAP_FAT_COMPRA (
         ID_COMPRA,        
         ID_ESTADO_CIVIL,
         ID_LOCAL,
         ID_DATA,
         ID_APARELHO,
         VALOR,
         QUANTIDADE
    )
    VALUES (
         SQ_OLAP_COMPRA.NEXTVAL,  
         v_id_estado_civil,
         v_id_local,
         v_id_data,
         v_id_aparelho,
         rec.VALOR,
         rec.QUANTIDADE
    );
    
  END LOOP;
  
  COMMIT;
  
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
    
END prc_popula_fat_compra;

EXEC prc_popula_fat_compra;


-- SELECTS PARA TESTES

SELECT * FROM COMPRA JOIN CARRINHO USING (ID_COMPRA) JOIN CLIENTE USING (ID_CLIENTE) JOIN APARELHO USING (ID_APARELHO) JOIN CIDADE USING (ID_CIDADE) JOIN MODELO MO USING (ID_MODELO);

SELECT 
    ESTADO_CIVIL,
    MO.DESCRICAO AS MODELO,
    CIDADE.DESCRICAO AS CIDADE,
    ESTADO.SIGLA AS ESTADO,
    EXTRACT(YEAR FROM DATA) AS ANO,
    CASE 
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
    END AS quadrimestre,
    COUNT(*) AS QUANTIDADE,
    SUM(valor) AS VALOR
FROM COMPRA 
    JOIN CARRINHO USING (ID_COMPRA) 
    JOIN CLIENTE USING (ID_CLIENTE) 
    JOIN APARELHO USING (ID_APARELHO) 
    JOIN CIDADE USING (ID_CIDADE) 
    JOIN MODELO MO USING (ID_MODELO) 
    JOIN ESTADO USING (ID_ESTADO)
GROUP BY
    ESTADO_CIVIL,
    MO.DESCRICAO,
    CIDADE.DESCRICAO,
    ESTADO.SIGLA,
    EXTRACT(YEAR FROM DATA),
    CASE 
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 1 AND 4 THEN 1
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 5 AND 8 THEN 2
        WHEN EXTRACT(MONTH FROM DATA) BETWEEN 9 AND 12 THEN 3
    END
ORDER BY 
    ANO,
    quadrimestre;


